models/Kpi.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "kpi".
 *
 * @property int $kpi_id
 * @property string|null $kpi_name
 * @property string|null $kpi_template
 * @property float|null $kpi_target
 * @property string|null $kpi_operate
 * @property string|null $kpi_owner
 * @property string|null $kpi_from
 */
class Kpi extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'kpi';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['kpi_template', 'kpi_operate'], 'string'],
            [['kpi_target'], 'number'],
            [['kpi_name', 'kpi_owner', 'kpi_from'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'kpi_id' => 'Kpi ID',
            'kpi_name' => 'รายการ KPI',
            'kpi_template' => 'Kpi Template',
            'kpi_target' => 'เป้าหมาย',
            'kpi_operate' => 'เครื่องหมาย',
            'kpi_owner' => 'ผู้รับผิดชอบ KPI',
            'kpi_from' => 'ที่มาของ KPI',
        ];
    }
}

controllers/KpiController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Kpi;
use app\models\KpiSearch;
use app\models\FeeTemplate;
use app\models\FeeTemplateSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * KpiController implements the CRUD actions for Kpi model.
 */
class KpiController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Kpi models.
     * @return mixed
     */
    public function actionFsindex()
    {
        $searchModel = new FeeTemplateSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('fs_index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all Kpi models.
     * @return mixed
     */
    public function actionKpiindex()
    {
        $searchModel = new KpiSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('kpi_index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Fee Template model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionFsview($id)
    {
        return $this->render('fs_view', [
            'model' => $this->findFsModel($id),
        ]);
    }

    /**
     * Displays a single Kpi model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionKpiview($id)
    {
        return $this->render('kpi_view', [
            'model' => $this->findKpiModel($id),
        ]);
    }

    /**
     * Creates a new Fee Template model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionFscreate()
    {
        $model = new FeeTemplate();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $searchModel = new FeeTemplateSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
    
            return $this->render('fs_index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }

        return $this->render('fs_create', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Kpi model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionKpicreate()
    {
        $model = new Kpi();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $searchModel = new KpiSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
    
            return $this->render('kpi_index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }

        return $this->render('kpi_create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Fee Template model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionFsupdate($id)
    {
        $model = $this->findFsModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $searchModel = new FeeTemplateSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
    
            return $this->render('fs_index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }

        return $this->render('fs_update', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Kpi model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionKpiupdate($id)
    {
        $model = $this->findKpiModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $searchModel = new KpiSearch();
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
    
            return $this->render('kpi_index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        }

        return $this->render('kpi_update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Fee Template model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionFsdelete($id)
    {
        $this->findFsModel($id)->delete();

        return $this->redirect(['fs_index']);
    }

    /**
     * Deletes an existing Kpi model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionKpidelete($id)
    {
        $this->findKpiModel($id)->delete();

        return $this->redirect(['kpi_index']);
    }

    /**
     * Finds the Kpi model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Kpi the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findKpiModel($id)
    {
        if (($model = Kpi::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Finds the Kpi model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Kpi the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findFsModel($id)
    {
        if (($model = FeeTemplate::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/kpi/_fs_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\FeeTemplate */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="fee-template-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'fee_schedule_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'template')->textarea(['rows' => 6]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/kpi/_fs_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\FeeTemplateSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="fee-template-search">

    <?php $form = ActiveForm::begin([
        'action' => ['fsindex'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'fee_schedule_id') ?>

    <?= $form->field($model, 'fee_schedule_name') ?>

    <?= $form->field($model, 'template') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/kpi/_kpi_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Kpi */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="kpi-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'kpi_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'kpi_template')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'kpi_target')->textInput() ?>

    <?= $form->field($model, 'kpi_operate')->dropDownList([ '=' => '=', '>=' => '>=', '<=' => '<=', '>' => '>', '<' => '<', ], ['prompt' => '']) ?>

    <?= $form->field($model, 'kpi_owner')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'kpi_from')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/kpi/_kpi_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\KpiSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="kpi-search">

    <?php $form = ActiveForm::begin([
        'action' => ['kpiindex'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'kpi_id') ?>

    <?= $form->field($model, 'kpi_name') ?>

    <?= $form->field($model, 'kpi_template') ?>

    <?= $form->field($model, 'kpi_target') ?>

    <?= $form->field($model, 'kpi_operate') ?>

    <?php // echo $form->field($model, 'kpi_owner') ?>

    <?php // echo $form->field($model, 'kpi_from') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/kpi/fs_create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\FeeTemplate */

$this->title = 'เพิ่ม Fee Schedule Template';
$this->params['breadcrumbs'][] = ['label' => 'Fee Templates', 'url' => ['fsindex']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="fee-template-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_fs_form', [
        'model' => $model,
    ]) ?>

</div>

views/kpi/fs_index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\FeeTemplateSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Fee Schedule Templates';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="fee-template-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('เพิ่ม Fee Schedule Template', ['fscreate'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_fs_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'fee_schedule_id',
            'fee_schedule_name',
            'template:ntext',
            [
                'class' => 'yii\grid\ActionColumn',
                'options'=>['style'=>'width:120px;'],
                'buttonOptions'=>['class'=>'btn btn-danger'],
                'template'=>'{edit}',
                'buttons'=>[
                    'edit' => function($url,$model,$key){
                      return Html::a('แก้ไข',['kpi/fsupdate','id'=>$model->fee_schedule_id],['class' => 'btn btn-warning']);
                    }
                ]
             ],

            //['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

views/kpi/fs_update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\FeeTemplate */

$this->title = 'Update Fee Template: ' . $model->fee_schedule_id;
$this->params['breadcrumbs'][] = ['label' => 'Fee Templates', 'url' => ['fsindex']];
$this->params['breadcrumbs'][] = ['label' => $model->fee_schedule_id, 'url' => ['fsview', 'id' => $model->fee_schedule_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="fee-template-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_fs_form', [
        'model' => $model,
    ]) ?>

</div>

views/kpi/fs_view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\FeeTemplate */

$this->title = $model->fee_schedule_id;
$this->params['breadcrumbs'][] = ['label' => 'Fee Templates', 'url' => ['fsindex']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="fee-template-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['fsupdate', 'id' => $model->fee_schedule_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['fsdelete', 'id' => $model->fee_schedule_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'fee_schedule_id',
            'fee_schedule_name',
            'template:ntext',
        ],
    ]) ?>

</div>

views/kpi/kpi_create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Kpi */

$this->title = 'เพิ่ม KPI';
$this->params['breadcrumbs'][] = ['label' => 'Kpis', 'url' => ['kpiindex']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="kpi-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_kpi_form', [
        'model' => $model,
    ]) ?>

</div>

views/kpi/kpi_index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\KpiSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'รายการ KPI';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="kpi-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('เพิ่ม KPI', ['kpicreate'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_kpi_ search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'kpi_id',
            'kpi_name',
            'kpi_template:ntext',
            'kpi_target',
            'kpi_operate',
            'kpi_owner',
            'kpi_from',
            [
                'class' => 'yii\grid\ActionColumn',
                'options'=>['style'=>'width:120px;'],
                'buttonOptions'=>['class'=>'btn btn-danger'],
                'template'=>'{edit}',
                'buttons'=>[
                    'edit' => function($url,$model,$key){
                      return Html::a('แก้ไข',['kpi/kpiupdate','id'=>$model->kpi_id],['class' => 'btn btn-warning']);
                    }
                ]
             ],

            // ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

views/kpi/kpi_update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Kpi */

$this->title = 'แก้ไข KPI: ' . $model->kpi_id;
$this->params['breadcrumbs'][] = ['label' => 'Kpis', 'url' => ['kpiindex']];
$this->params['breadcrumbs'][] = ['label' => $model->kpi_id, 'url' => ['kpiview', 'id' => $model->kpi_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="kpi-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_kpi_form', [
        'model' => $model,
    ]) ?>

</div>

views/kpi/kpi_view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Kpi */

$this->title = $model->kpi_id;
$this->params['breadcrumbs'][] = ['label' => 'Kpis', 'url' => ['kpiindex']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="kpi-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['kpiupdate', 'id' => $model->kpi_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['kpidelete', 'id' => $model->kpi_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'kpi_id',
            'kpi_name',
            'kpi_template:ntext',
            'kpi_target',
            'kpi_operate',
            'kpi_owner',
            'kpi_from',
        ],
    ]) ?>

</div>