controllers/SummaryController.php
<?php

namespace app\controllers;

use Yii;
use app\models\SummaryReport;
use app\models\SummaryReportSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SummaryController implements the CRUD actions for SummaryReport model.
 */
class SummaryController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all SummaryReport models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SummaryReportSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single SummaryReport model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new SummaryReport model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new SummaryReport();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->yearbudget]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing SummaryReport model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->yearbudget]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing SummaryReport model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the SummaryReport model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return SummaryReport the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = SummaryReport::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/summary/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\SummaryReport */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="summary-report-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'yearbudget')->textInput() ?>

    <?= $form->field($model, 'op_visit')->textInput() ?>

    <?= $form->field($model, 'op_hn')->textInput() ?>

    <?= $form->field($model, 'op_per_day')->textInput() ?>

    <?= $form->field($model, 'op_refer')->textInput() ?>

    <?= $form->field($model, 'op_death')->textInput() ?>

    <?= $form->field($model, 'op_accdent')->textInput() ?>

    <?= $form->field($model, 'op_head_injury')->textInput() ?>

    <?= $form->field($model, 'op_stroke')->textInput() ?>

    <?= $form->field($model, 'op_stemi')->textInput() ?>

    <?= $form->field($model, 'ip_admit')->textInput() ?>

    <?= $form->field($model, 'ip_refer')->textInput() ?>

    <?= $form->field($model, 'ip_losd')->textInput() ?>

    <?= $form->field($model, 'ip_bed_rate')->textInput() ?>

    <?= $form->field($model, 'ip_sum_adjrw')->textInput() ?>

    <?= $form->field($model, 'ip_cmi')->textInput() ?>

    <?= $form->field($model, 'op_uc')->textInput() ?>

    <?= $form->field($model, 'op_sss')->textInput() ?>

    <?= $form->field($model, 'op_lgo')->textInput() ?>

    <?= $form->field($model, 'op_ofc')->textInput() ?>

    <?= $form->field($model, 'op_other')->textInput() ?>

    <?= $form->field($model, 'ip_uc')->textInput() ?>

    <?= $form->field($model, 'ip_sss')->textInput() ?>

    <?= $form->field($model, 'ip_lgo')->textInput() ?>

    <?= $form->field($model, 'ip_ofc')->textInput() ?>

    <?= $form->field($model, 'ip_other')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/summary/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\SummaryReportSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="summary-report-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'summary_id') ?>

    <?= $form->field($model, 'yearbudget') ?>

    <?= $form->field($model, 'op_visit') ?>

    <?= $form->field($model, 'op_hn') ?>

    <?= $form->field($model, 'op_per_day') ?>

    <?php // echo $form->field($model, 'op_refer') ?>

    <?php // echo $form->field($model, 'op_death') ?>

    <?php // echo $form->field($model, 'op_accdent') ?>

    <?php // echo $form->field($model, 'op_head_injury') ?>

    <?php // echo $form->field($model, 'op_stroke') ?>

    <?php // echo $form->field($model, 'op_stemi') ?>

    <?php // echo $form->field($model, 'ip_admit') ?>

    <?php // echo $form->field($model, 'ip_dc') ?>

    <?php // echo $form->field($model, 'ip_refer') ?>

    <?php // echo $form->field($model, 'ip_losd') ?>

    <?php // echo $form->field($model, 'ip_bed_rate') ?>

    <?php // echo $form->field($model, 'ip_sum_adjrw') ?>

    <?php // echo $form->field($model, 'ip_cmi') ?>

    <?php // echo $form->field($model, 'op_uc') ?>

    <?php // echo $form->field($model, 'op_sss') ?>

    <?php // echo $form->field($model, 'op_lgo') ?>

    <?php // echo $form->field($model, 'op_ofc') ?>

    <?php // echo $form->field($model, 'op_prb') ?>

    <?php // echo $form->field($model, 'op_other') ?>

    <?php // echo $form->field($model, 'ip_uc') ?>

    <?php // echo $form->field($model, 'ip_sss') ?>

    <?php // echo $form->field($model, 'ip_lgo') ?>

    <?php // echo $form->field($model, 'ip_ofc') ?>

    <?php // echo $form->field($model, 'ip_other') ?>

    <?php // echo $form->field($model, 'd_update') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/summary/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\SummaryReport */

$this->title = 'Create Summary Report';
$this->params['breadcrumbs'][] = ['label' => 'Summary Reports', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="summary-report-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/summary/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\SummaryReportSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'รายงานสรุป';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="summary-report-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('เพิ่มรายงานสรุป', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        // 'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'summary_id',
            'yearbudget',
            'op_visit',
            //'op_hn',
            //'op_per_day',
            'op_refer',
            //'op_death',
            //'op_accdent',
            //'op_head_injury',
            //'op_stroke',
            //'op_stemi',
            'ip_admit',
            //'ip_dc',
            'ip_refer',
            //'ip_losd',
            //'ip_bed_rate',
            'ip_sum_adjrw',
            'ip_cmi',
            //'op_uc',
            //'op_sss',
            //'op_lgo',
            //'op_ofc',
            //'op_prb',
            //'op_other',
            //'ip_uc',
            //'ip_sss',
            //'ip_lgo',
            //'ip_ofc',
            //'ip_other',
            //'d_update',

            [
                'class' => 'yii\grid\ActionColumn',
                'options'=>['style'=>'width:120px;'],
                'buttonOptions'=>['class'=>'btn btn-danger'],
                'template'=>'{update}',
                'buttons'=>[
                    'update' => function($url,$model,$key){
                      return Html::a('แก้ไข',['summary/update','id'=>$model->yearbudget],['class' => 'btn btn-warning']);
                    }
                ]
             ],
        ],

    ]); ?>


</div>

views/summary/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\SummaryReport */

$this->title = 'Update Summary Report: ' . $model->yearbudget;
$this->params['breadcrumbs'][] = ['label' => 'Summary Reports', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->yearbudget, 'url' => ['view', 'id' => $model->yearbudget]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="summary-report-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/summary/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\SummaryReport */

$this->title = $model->yearbudget;
$this->params['breadcrumbs'][] = ['label' => 'Summary Reports', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="summary-report-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->yearbudget], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->yearbudget], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'yearbudget',
            'op_visit',
            'op_hn',
            'op_per_day',
            'op_refer',
            'op_death',
            'op_accdent',
            'op_head_injury',
            'op_stroke',
            'op_stemi',
            'ip_admit',
            'ip_refer',
            'ip_losd',
            'ip_bed_rate',
            'ip_sum_adjrw',
            'ip_cmi',
            'op_uc',
            'op_sss',
            'op_lgo',
            'op_ofc',
            'op_other',
            'ip_uc',
            'ip_sss',
            'ip_lgo',
            'ip_ofc',
            'ip_other',
            'd_update',
        ],
    ]) ?>

</div>